### PR TITLE
Added computer engineering

### PR DESCRIPTION
**Pull request by xforever1313**
Added a page for Computer Engineering, which includes some useful FOSS software (...and one that is not but it is very helpful).

### CODE REVIEW

**Comment by MoralCode** [comment]
@catarial do you want to add anything to this PR before I merge it? seemed like you had a lot to add for specific CE classes

**Comment by MoralCode** [comment]
oh, like have CE be a subdirectory with specific sub-guides, like how the eduroam stuff is laid out? gotcha

**Comment by xforever1313** [comment]
Honestly, it may not be a bad idea to do that for all majors, instead of having one page at the root layer.

**Comment by MoralCode** [comment]
yep, thats exactly what i was just doing - although i cannot seem to push to the branch that this PR is based on for some reason

**Comment by MoralCode** [comment]
hmm, i still dont seem to have permission so ill just merge this and make the changes afterwards

**Pull request merged**
